Updates to vue3 templatetag for supporting Vite build
CentreForDigitalHumanities/django-shared-core pull request #88
Opened 2023-10-06 07:46 UTC by bbonf

See also https://github.com/UiL-OTS-labs/babex/pull/121

2023-10-06 11:54 UTC, tymees requested changes
I like the idea, I was missing something like this and was planning on writing it myself.

However, I would like it to be a bit more modular/configurable

2023-10-06 11:54 UTC, tymees commented on src/cdh/vue3/templatetags/vue3.py
> +        manifest = json.load(f)
This only makes sense if you only have the one Vue app for the entire app; this will clash with the use-cases that DSC itself will encounter; (Multiple components, only some of which are useful for any given app).

Ideally, you can specify manifests in a more configurable way; in the Vue 2 app I build a 'app registry', which is just a simple class with info like this, grouped together under a single identifier one can use to load all you need. Something like that would be nicer

2023-10-06 11:54 UTC, tymees commented on src/cdh/vue3/templatetags/vue3.py
> +        static = settings.VUE_URL
Why not use Django's built-in static resolving instead?

2023-10-06 12:05 UTC, tymees commented
(To explain my registry thing a bit more)

In this case would just be a simple singleton class, that is populated by adding a key-value to it in the `app.py` of individual Django apps. See also:
https://github.com/DH-IT-Portal-Development/django-shared-core/blob/master/src/cdh/vue/components.py

2023-10-12 12:44 UTC, bbonf commented on src/cdh/vue3/templatetags/vue3.py
> +        manifest = json.load(f)
What does vite do in that use case? Separate modules per component with separate manifests?

2023-10-12 12:53 UTC, tymees commented on src/cdh/vue3/templatetags/vue3.py
> +        manifest = json.load(f)
In that case, there would be seperate (semi-)independent vite builds, so you would get separate manifests per 'app'.

For example, you get separate manifests for:
- The default List-view
- Any custom List-view
- Vue-powered form-widgets

2025-02-18 09:34 UTC, bbonf commented
closing this because in the meantime there've been more (minor) divergences with https://github.com/UiL-OTS-labs/django-vue3-tag which should be prepared for upstreaming

2025-02-18 09:34 UTC, closed without merging